# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6223a63d315ce8dfc28dab1b3b5d9b3c214245351a5a18f07c03d8055ed77ea51c753a2f3cafe25db934a3905d66276b45a12c8ef841682a120963168353f7

test:
  secret_key_base: 78e9585934e2dc1f239952ac1fb64779a797adb8485ce09fd4c8a6a0827897e3ed6620536df23954b225d7ef4662018dd9b9e1dda71323c4746765ff982fa33e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
