# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f67bf8bdbf9148a4b07ae9acca6ba2378f5e142a9eedc1981a4598ddcb8533a53699d15e202301efde2ec64734f74e041ec53c360da41b564c837a66484cebd

test:
  secret_key_base: cdd0dde1f286bfe73a4398a302c3a70325c748a8109f44f564d88bc4ade4f7d44bbcd6bc1a892e263024747f2d6930f10b99fc56b6c61794a2ef9d651af102a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
