# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7512cb43b9c2cd20a14ce3d93b267779f0853d0c82c8625a4959bc9012cd716182dd6910564773a608623ec1fec6ad544f10146408f0c639370e7bbf3160b3a

test:
  secret_key_base: 5055b26cac1803f0e81e3bd61b10a7125774652134bdad733a1dc7a6214d277e0de2f7e25e89484189e8c5abdab5dc25568f6a67fd702bd8a7e99c571240074d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
